### ISSUE TITLE
Highlighting issue with macros

### ISSUE THREAD

**Issue by acheroncrypto** [lezer-parser/rust#1]
Using a keyword inside an attribute macro results in corrupted highlighting and unwanted indentation on next line.

Example: 
![image](https://user-images.githubusercontent.com/98934430/164944416-1181419a-a9ce-4b82-8f05-c37fed09236e.png)

Quotes are able to stop the highlighting issue but indentation on next line persists.
![image](https://user-images.githubusercontent.com/98934430/164944461-a71b3a8a-ed36-494a-b1de-603c8eaed165.png)

[Example code](https://github.com/project-serum/anchor/blob/master/examples/tutorial/basic-2/programs/basic-2/src/lib.rs#L34)

**Comment by marijnh** [comment]
It would have made figuring out what you mean a lot easier if you had presented valid rust code, instead of a bunch of code that is invalid in ways that have nothing to do with what you mean here.

But I guess what you wanted to say is that something like `#[foo(mut)]` should be valid. Attached patch fixes that.

**Comment by acheroncrypto** [comment]
Thank you but I had already attached a valid code at the end. `#[foo(mut)]` was actually not causing any issues. The issue started when there is a comma after the `mut` like in the example I've sent `#[account(mut, has_one = authority)]`.

Don't know if the issue is fixed as the package is not yet updated but thank you.
